SELECT * FROM EMPLEADOS
SELECT NOMBRE FROM PUESTOS
SELECT * FROM EMPLEADOS WHERE ESTA_ACTIVO = 1
SELECT * FROM EMPLEADOS WHERE SALARIO > 200000
SELECT * FROM EMPLEADOS WHERE FECHA_ALTA <= '2021-07-06'
SELECT * FROM EMPLEADOS WHERE MAIL IS NULL
SELECT * FROM EMPLEADOS WHERE MAIL IS NOT NULL
SELECT * FROM EMPLEADOS WHERE MAIL LIKE '%gmail%'
SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'B%'