SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO
SELECT * FROM EMPLEADOS e INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO WHERE p.NIVEL_AUTORIZACION = 3
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO ORDER BY e.APELLIDO
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO ORDER BY p.NIVEL_AUTORIZACION

SELECT p.NIVEL_AUTORIZACION, p.ID_PUESTO,p.NOMBRE FROM PUESTOS p LEFT JOIN EMPLEADOS e 
ON p.ID_PUESTO = e.ID_PUESTO WHERE e.ID_PUESTO IS NULL

SELECT p.NIVEL_AUTORIZACION, p.ID_PUESTO,p.NOMBRE FROM PUESTOS p LEFT JOIN EMPLEADOS e 
ON p.ID_PUESTO = e.ID_PUESTO WHERE e.ID_PUESTO IS NOT NULL