INSERT INTO PRODUCTOS (CODIGO_PRODUCTO,NOMBRE,PRECIO,DIMENSIONES) VALUES (4,'Chocolate', 23.35,'Chico')
SELECT * FROM PRODUCTOS

INSERT INTO PROVEEDORES (NUMERO_PROVEEDOR) VALUES (50)
SELECT * FROM PROVEEDORES

INSERT INTO PROVEEDORES (NUMERO_PROVEEDOR,NOMBRE,LOCALIDAD) VALUES (107, 'Rosales','La Plata')
SELECT * FROM PROVEEDORES

UPDATE PRODUCTOS SET PRECIO=97.50 WHERE DIMENSIONES='grande'

UPDATE PRODUCTOS SET DIMENSIONES='Mediano' WHERE CODIGO_PRODUCTO=(SELECT p.CODIGO_PRODUCTO FROM ENVIOS e INNER JOIN PRODUCTOS p ON e.CODIGO_PRODUCTO=p.CODIGO_PRODUCTO WHERE e.CANTIDAD>300 AND p.DIMENSIONES='Chico')
