SELECT * FROM PRODUCTOS ORDER BY NOMBRE
SELECT * FROM PROVEEDORES WHERE LOCALIDAD = 'Quilmes'
SELECT * FROM ENVIOS WHERE CANTIDAD BETWEEN 200 AND 300
SELECT COUNT(*) FROM ENVIOS
SELECT TOP(3) CODIGO_PRODUCTO FROM ENVIOS
SELECT p.NOMBRE,x.NOMBRE FROM PROVEEDORES p INNER JOIN ENVIOS e ON p.NUMERO_PROVEEDOR = e.NUMERO_PROVEEDOR
INNER JOIN PRODUCTOS x ON e.CODIGO_PRODUCTO = x.CODIGO_PRODUCTO
SELECT e.CANTIDAD * p.PRECIO FROM ENVIOS e INNER JOIN PRODUCTOS p ON e.CODIGO_PRODUCTO = p.CODIGO_PRODUCTO
SELECT SUM(CANTIDAD) FROM ENVIOS WHERE CODIGO_PRODUCTO=1 AND NUMERO_PROVEEDOR=102
SELECT CODIGO_PRODUCTO FROM ENVIOS e INNER JOIN PROVEEDORES p ON p.NUMERO_PROVEEDOR = e.NUMERO_PROVEEDOR WHERE e.NUMERO_PROVEEDOR=101
SELECT DOMICILIO,LOCALIDAD FROM PROVEEDORES WHERE NOMBRE LIKE '%i%'