SELECT AVG(SALARIO) FROM EMPLEADOS WHERE ESTA_ACTIVO=1;
SELECT SUM(SALARIO) FROM EMPLEADOS WHERE ESTA_ACTIVO=1;
SELECT COUNT(*) FROM EMPLEADOS WHERE SALARIO > 250000;
SELECT COUNT(*) FROM EMPLEADOS WHERE FECHA_ALTA < '2010-01-01';
SELECT MAX(SALARIO) FROM EMPLEADOS;
SELECT NOMBRE FROM PUESTOS WHERE NIVEL_AUTORIZACION =  (SELECT MIN(NIVEL_AUTORIZACION) FROM PUESTOS);
SELECT CONCAT (NOMBRE,' ',APELLIDO) AS nombre_completo FROM EMPLEADOS;
SELECT CONCAT(e.NOMBRE,' ',e.APELLIDO) AS nombre_completo ,p.NOMBRE,p.NIVEL_AUTORIZACION FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO;
SELECT CONCAT(e.NOMBRE,' ',e.APELLIDO) AS nombre_completo ,p.NOMBRE,p.NIVEL_AUTORIZACION FROM EMPLEADOS e RIGHT JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO;
