SELECT * FROM EMPLEADOS;
SELECT * FROM PUESTOS;
SELECT e.NOMBRE,e.APELLIDO, p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO;
SELECT *, p.NIVEL_AUTORIZACION FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO WHERE p.NIVEL_AUTORIZACION =3;
SELECT e.NOMBRE,e.APELLIDO,p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO ORDER BY APELLIDO;
SELECT e.NOMBRE,e.APELLIDO,p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO ORDER BY p.NOMBRE;
SELECT e.NOMBRE,e.APELLIDO,p.NOMBRE FROM EMPLEADOS e INNER JOIN PUESTOS p ON p.ID_PUESTO = e.ID_PUESTO WHERE ESTA_ACTIVO=1 ORDER BY p.NIVEL_AUTORIZACION;
SELECT p.NOMBRE, p.ID_PUESTO,p.NIVEL_AUTORIZACION FROM PUESTOS p LEFT JOIN EMPLEADOS e ON p.ID_PUESTO = e.ID_PUESTO WHERE e.ID_PUESTO IS NULL;
SELECT p.NOMBRE, p.ID_PUESTO,p.NIVEL_AUTORIZACION FROM PUESTOS p LEFT JOIN EMPLEADOS e ON p.ID_PUESTO = e.ID_PUESTO WHERE e.ID_PUESTO IS NOT NULL;