UPDATE EMPLEADOS SET MAIL ='mbrock@google.com' WHERE ID_EMPLEADO = 4;
UPDATE EMPLEADOS SET ID_PUESTO = (SELECT ID_PUESTO FROM PUESTOS WHERE NOMBRE = 'Administrativo'), SALARIO= 210000 WHERE ID_EMPLEADO = 10;
UPDATE EMPLEADOS SET SALARIO = SALARIO/0.75 FROM EMPLEADOS WHERE SALARIO < 250000;
UPDATE EMPLEADOS SET FECHA_BAJA = '2022-05-22' FROM EMPLEADOS WHERE ID_EMPLEADO=1;
DELETE FROM EMPLEADOS WHERE ESTA_ACTIVO = 0;